# Script for CI/CD on gitlab instances.
#
image: alpine

pages:
  script:
  - apk --no-cache add python3 python3-dev py3-pip make rsync
  - cd docgen 
  - pip3 install -r requirements.txt
  - make html
  - mv _build/html ../public
  artifacts:
    paths:
    - public
  only:
  - master
